stream_policy:
  live_stream_profile: "NORMAL"
  enable_adaptive_profile: true
  focus_view_profile: "HD"
  grid_view_profile: "NORMAL"
  mobile_view_profile: "MOBILE"
  playback_profile: "HD"
  playback_allow_normal_fallback: true
  playback_allow_mobile_fallback: false
  viewer_grace_seconds: 5
  stream_grace_seconds: 60
  enable_sd_card_on_demand: false
  sd_card_on_demand_retention_seconds: 3600
