"""
camera_policy.py — Backward-Compatibility Shim

All policy constants have been consolidated into vms_policy.py.
This file re-exports them so existing imports in stream_manager, recording_provider,
camera_watchdog, etc. continue to work without changes.

To change any policy, edit: backend/app/vms_policy.py
To use env overrides, set the corresponding variable in: backend/.env
"""

# Re-export everything from the centralized policy module
from .vms_policy import (
    # Source validation
    STRICT_CAMERA_VALIDATION,
    ALLOW_UNKNOWN_EDGE_DEVICES,

    # Recording
    RECORD_HD_ONLY,
    RECORD_NORMAL,
    RECORD_MOBILE,
    get_recording_profiles,
    should_record_profile,

    # Live streaming
    LIVE_STREAM_PROFILE,
    ENABLE_ADAPTIVE_PROFILE,
    FOCUS_VIEW_PROFILE,
    GRID_VIEW_PROFILE,
    MOBILE_VIEW_PROFILE,
    resolve_live_profile,

    # Playback
    PLAYBACK_PROFILE,
    PLAYBACK_ALLOW_NORMAL_FALLBACK,
    PLAYBACK_ALLOW_MOBILE_FALLBACK,
    PLAYBACK_SPEEDS,
    resolve_playback_profile,

    # WebRTC
    ENABLE_WEBRTC,
    ENABLE_HLS_FALLBACK,
    WEBRTC_CONNECTION_TIMEOUT_SECONDS,
    MAX_WEBRTC_SESSIONS_PER_CAMERA,

    # H.265 transcoding
    ENABLE_H265_TRANSCODING,
    TRANSCODER_VCODEC,
    TRANSCODER_PRESET,
    TRANSCODER_TUNE,
    TRANSCODER_IDLE_TIMEOUT_SECONDS,
    MAX_ACTIVE_TRANSCODERS,

    # Recording segments
    SEGMENT_DURATION_SECONDS,
    ENABLE_RECORDING,
    RECORDING_RECOVERY_INTERVAL_HOURS,

    # Timeline
    TIMELINE_CACHE_SECONDS,
    TIMELINE_MERGE_THRESHOLD_SECONDS,
    TIMELINE_DEFAULT_ZOOM,

    # Edge push
    ENABLE_EDGE_PUSH,
    EDGE_PUSH_PRIORITY,
    EDGE_PUSH_HEARTBEAT_TIMEOUT_SECONDS,
    EDGE_PUSH_CHECK_INTERVAL_SECONDS,

    # RTSP watchdog
    ENABLE_RTSP_HEALTH_CHECK,
    CAMERA_PING_INTERVAL_SECONDS,
    CAMERA_PING_TIMEOUT_SECONDS,
    CAMERA_PING_MAX_CONCURRENT,

    # Upstream sync
    UPSTREAM_SYNC_INTERVAL_HOURS,

    # Storage retention
    ENABLE_RETENTION,
    DEFAULT_RETENTION_DAYS,

    # MediaMTX safety
    MEDIAMTX_PATCH_ONLY,
    ALLOW_DELETE_ADD_RECONFIGURATION,

    # Profile map
    PROFILE_MAP,
)

__all__ = [
    "STRICT_CAMERA_VALIDATION", "ALLOW_UNKNOWN_EDGE_DEVICES",
    "RECORD_HD_ONLY", "RECORD_NORMAL", "RECORD_MOBILE",
    "get_recording_profiles", "should_record_profile",
    "LIVE_STREAM_PROFILE", "ENABLE_ADAPTIVE_PROFILE",
    "FOCUS_VIEW_PROFILE", "GRID_VIEW_PROFILE", "MOBILE_VIEW_PROFILE",
    "resolve_live_profile",
    "PLAYBACK_PROFILE", "PLAYBACK_ALLOW_NORMAL_FALLBACK",
    "PLAYBACK_ALLOW_MOBILE_FALLBACK", "PLAYBACK_SPEEDS",
    "resolve_playback_profile",
    "ENABLE_WEBRTC", "ENABLE_HLS_FALLBACK",
    "WEBRTC_CONNECTION_TIMEOUT_SECONDS", "MAX_WEBRTC_SESSIONS_PER_CAMERA",
    "ENABLE_H265_TRANSCODING", "TRANSCODER_VCODEC", "TRANSCODER_PRESET",
    "TRANSCODER_TUNE", "TRANSCODER_IDLE_TIMEOUT_SECONDS", "MAX_ACTIVE_TRANSCODERS",
    "SEGMENT_DURATION_SECONDS", "ENABLE_RECORDING", "RECORDING_RECOVERY_INTERVAL_HOURS",
    "TIMELINE_CACHE_SECONDS", "TIMELINE_MERGE_THRESHOLD_SECONDS", "TIMELINE_DEFAULT_ZOOM",
    "ENABLE_EDGE_PUSH", "EDGE_PUSH_PRIORITY",
    "EDGE_PUSH_HEARTBEAT_TIMEOUT_SECONDS", "EDGE_PUSH_CHECK_INTERVAL_SECONDS",
    "ENABLE_RTSP_HEALTH_CHECK", "CAMERA_PING_INTERVAL_SECONDS",
    "CAMERA_PING_TIMEOUT_SECONDS", "CAMERA_PING_MAX_CONCURRENT",
    "UPSTREAM_SYNC_INTERVAL_HOURS",
    "ENABLE_RETENTION", "DEFAULT_RETENTION_DAYS",
    "MEDIAMTX_PATCH_ONLY", "ALLOW_DELETE_ADD_RECONFIGURATION",
    "PROFILE_MAP",
]
